# Generated by Django 5.2.15 on 2026-07-09 21:33

import accounts.models.user
from django.db import migrations, models


def normalizar_usuarios_email(apps, _schema_editor):
    User = apps.get_model("accounts", "User")
    emails_por_usuario = []

    for usuario in User.objects.all().only("id", "email", "username"):
        email = (usuario.email or "").strip().lower()
        username = (usuario.username or "").strip().lower()

        if not email and "@" in username:
            email = username

        if not email:
            raise RuntimeError(
                f"Usuario {usuario.id} nao possui email para migracao de autenticacao."
            )

        emails_por_usuario.append((usuario.id, email))

    emails_vistos = set()
    emails_duplicados = set()
    for _usuario_id, email in emails_por_usuario:
        if email in emails_vistos:
            emails_duplicados.add(email)
        emails_vistos.add(email)

    if emails_duplicados:
        duplicados = ", ".join(sorted(emails_duplicados))
        raise RuntimeError(f"Emails duplicados impedem migracao de autenticacao: {duplicados}")

    for usuario_id, email in emails_por_usuario:
        User.objects.filter(id=usuario_id).update(email=email, username=email)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.UserManager()),
            ],
        ),
        migrations.RunPython(normalizar_usuarios_email, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=254, unique=True),
        ),
    ]
