# Generated by Django 5.2.15 on 2026-06-04 23:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('produtos', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem_apontamento', models.CharField(choices=[('operador_qr', 'Operador QR'), ('operador_manual', 'Operador manual'), ('supervisor_manual', 'Supervisor manual')], default='operador_qr', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='cadastros.maquina')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_producao', to='cadastros.operacao')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_producao', to='accounts.operador')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='produtos.produto')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='turnos.turno')),
                ('turno_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='turnos.turnoop')),
                ('turno_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='turnos.turnosetor')),
                ('turno_setor_demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='turnos.turnosetordemanda')),
                ('turno_setor_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='turnos.turnosetoroperacao')),
                ('usuario_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_lancados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['turno', 'hora_registro'], name='producao_re_turno_i_b9e778_idx'), models.Index(fields=['operador', 'hora_registro'], name='producao_re_operado_4c88cb_idx'), models.Index(fields=['turno_op', 'operacao'], name='producao_re_turno_o_0b68c0_idx'), models.Index(fields=['turno_setor_operacao'], name='producao_re_turno_s_a56aac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='registro_qtd_gt0')],
            },
        ),
    ]
