# Generated by Django 5.2.15 on 2026-06-04 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('data_hora_abertura', models.DateTimeField()),
                ('data_hora_encerramento', models.DateTimeField(blank=True, null=True)),
                ('operadores_disponiveis', models.PositiveIntegerField()),
                ('minutos_turno', models.PositiveIntegerField()),
                ('meta_grupo', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_encerrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoOp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_op', models.CharField(max_length=50)),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('quantidade_planejada_remanescente', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_realizada', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('encerrada', 'Encerrada')], default='planejada', max_length=30)),
                ('tp_produto_min_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_ops', to='produtos.produto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops', to='turnos.turno')),
                ('turno_op_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_herdeiros', to='turnos.turnoop')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoOperador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='accounts.operador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_alocados', to='cadastros.setor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='turnos.turno')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoSetor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('encerrado', 'Encerrado')], default='aberto', max_length=30)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_setores', to='cadastros.setor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='turnos.turno')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoSetorOp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('quantidade_realizada', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('encerrada_manualmente', 'Encerrada manualmente')], default='aberta', max_length=30)),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor_ops_legado', to='cadastros.setor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_ops_legado', to='turnos.turno')),
                ('turno_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_ops_legado', to='turnos.turnoop')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoSetorDemanda',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_herdada_setor', models.PositiveIntegerField(default=0)),
                ('quantidade_liberada_setor', models.PositiveIntegerField(default=0)),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('quantidade_realizada', models.PositiveIntegerField(default=0)),
                ('quantidade_aceita_turno', models.PositiveIntegerField(default=0)),
                ('quantidade_excedente_turno', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor_demandas', to='produtos.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setor_demandas', to='cadastros.setor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_demandas', to='turnos.turno')),
                ('turno_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_demandas', to='turnos.turnoop')),
                ('turno_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='turnos.turnosetor')),
                ('turno_setor_op_legacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demanda_setorial', to='turnos.turnosetorop')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoSetorOperacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencia', models.PositiveIntegerField()),
                ('produto_operacao_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('versao_roteiro_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_padrao_min_snapshot', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantidade_planejada', models.PositiveIntegerField()),
                ('quantidade_realizada', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('encerrada_manualmente', 'Encerrada manualmente')], default='aberta', max_length=30)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_operacoes', to='cadastros.operacao')),
                ('produto_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turno_operacoes', to='produtos.produtooperacao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_operacoes', to='cadastros.setor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_operacoes', to='turnos.turno')),
                ('turno_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_operacoes', to='turnos.turnoop')),
                ('turno_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='turnos.turnosetor')),
                ('turno_setor_demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='turnos.turnosetordemanda')),
                ('turno_setor_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='turnos.turnosetorop')),
            ],
            options={
                'ordering': ['turno_setor_demanda', 'sequencia'],
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['status', 'data_hora_abertura'], name='turnos_turn_status_fcadc3_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['data_hora_encerramento'], name='turnos_turn_data_ho_2db326_idx'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('status',), name='uniq_turno_aberto'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('operadores_disponiveis__gt', 0)), name='turno_operadores_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_turno__gt', 0)), name='turno_minutos_gt0'),
        ),
        migrations.AddIndex(
            model_name='turnoop',
            index=models.Index(fields=['turno', 'status'], name='turnos_turn_turno_i_dc7ded_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoop',
            index=models.Index(fields=['numero_op'], name='turnos_turn_numero__ebee45_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoop',
            index=models.Index(fields=['produto'], name='turnos_turn_produto_04f511_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnoop',
            constraint=models.UniqueConstraint(fields=('turno', 'numero_op'), name='uniq_turno_numero_op'),
        ),
        migrations.AddConstraint(
            model_name='turnoop',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_planejada__gt', 0)), name='turno_op_qtd_plan_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turnoop',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_realizada__gte', 0)), name='turno_op_qtd_real_gte0'),
        ),
        migrations.AddIndex(
            model_name='turnooperador',
            index=models.Index(fields=['turno', 'setor'], name='turnos_turn_turno_i_6d0113_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnooperador',
            constraint=models.UniqueConstraint(fields=('turno', 'operador'), name='uniq_turno_operador'),
        ),
        migrations.AddIndex(
            model_name='turnosetor',
            index=models.Index(fields=['turno', 'status'], name='turnos_turn_turno_i_d3c4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetor',
            index=models.Index(fields=['setor'], name='turnos_turn_setor_i_93100a_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetor',
            index=models.Index(fields=['qr_code_token'], name='turnos_turn_qr_code_8d2675_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnosetor',
            constraint=models.UniqueConstraint(fields=('turno', 'setor'), name='uniq_turno_setor'),
        ),
        migrations.AddIndex(
            model_name='turnosetorop',
            index=models.Index(fields=['turno', 'status'], name='turnos_turn_turno_i_08e024_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetorop',
            index=models.Index(fields=['setor'], name='turnos_turn_setor_i_b15689_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetorop',
            index=models.Index(fields=['qr_code_token'], name='turnos_turn_qr_code_7c9cab_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnosetorop',
            constraint=models.UniqueConstraint(fields=('turno_op', 'setor'), name='uniq_turno_op_setor_leg'),
        ),
        migrations.AddConstraint(
            model_name='turnosetorop',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_planejada__gt', 0)), name='tso_qtd_plan_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turnosetorop',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_realizada__gte', 0)), name='tso_qtd_real_gte0'),
        ),
        migrations.AddIndex(
            model_name='turnosetordemanda',
            index=models.Index(fields=['turno', 'setor'], name='turnos_turn_turno_i_ec8634_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetordemanda',
            index=models.Index(fields=['turno_op'], name='turnos_turn_turno_o_f61294_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetordemanda',
            index=models.Index(fields=['produto'], name='turnos_turn_produto_f3ef54_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnosetordemanda',
            constraint=models.UniqueConstraint(fields=('turno_setor', 'turno_op'), name='uniq_demanda_setor_op'),
        ),
        migrations.AddConstraint(
            model_name='turnosetordemanda',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_planejada__gt', 0)), name='demanda_qtd_plan_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turnosetordemanda',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_realizada__gte', 0)), name='demanda_qtd_real_gte0'),
        ),
        migrations.AddIndex(
            model_name='turnosetoroperacao',
            index=models.Index(fields=['turno', 'status'], name='turnos_turn_turno_i_72e7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetoroperacao',
            index=models.Index(fields=['turno_op', 'operacao'], name='turnos_turn_turno_o_dc6ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetoroperacao',
            index=models.Index(fields=['turno_setor', 'status'], name='turnos_turn_turno_s_cf9dde_idx'),
        ),
        migrations.AddIndex(
            model_name='turnosetoroperacao',
            index=models.Index(fields=['setor', 'operacao'], name='turnos_turn_setor_i_f829a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnosetoroperacao',
            constraint=models.UniqueConstraint(fields=('turno_setor_demanda', 'operacao'), name='uniq_demanda_operacao'),
        ),
        migrations.AddConstraint(
            model_name='turnosetoroperacao',
            constraint=models.UniqueConstraint(fields=('turno_setor_demanda', 'sequencia'), name='uniq_demanda_sequencia'),
        ),
        migrations.AddConstraint(
            model_name='turnosetoroperacao',
            constraint=models.CheckConstraint(condition=models.Q(('tempo_padrao_min_snapshot__gt', 0)), name='tsope_tp_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turnosetoroperacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_planejada__gt', 0)), name='tsope_qtd_plan_gt0'),
        ),
        migrations.AddConstraint(
            model_name='turnosetoroperacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_realizada__gte', 0)), name='tsope_qtd_real_gte0'),
        ),
    ]
