# Generated by Django 5.2.15 on 2026-06-04 23:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeDefeito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('classificacao', models.CharField(choices=[('maquina', 'Maquina'), ('operador', 'Operador'), ('processo', 'Processo'), ('materia_prima', 'Materia-prima')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo', 'nome'], name='qualidade_q_ativo_4481ce_idx'), models.Index(fields=['classificacao'], name='qualidade_q_classif_c8b0ba_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('nome',), name='uniq_defeito_ativo_nome')],
            },
        ),
        migrations.CreateModel(
            name='QualidadeRegistro',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_aprovada', models.PositiveIntegerField(default=0)),
                ('quantidade_reprovada', models.PositiveIntegerField(default=0)),
                ('hora_revisao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_qualidade', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_qualidade', to='turnos.turno')),
                ('turno_op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_qualidade', to='turnos.turnoop')),
                ('turno_setor_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_qualidade', to='turnos.turnosetoroperacao')),
            ],
        ),
        migrations.CreateModel(
            name='QualidadeDetalhe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_defeito', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('defeito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='qualidade.qualidadedefeito')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos_qualidade', to='cadastros.operacao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos_qualidade', to='cadastros.setor')),
                ('turno_setor_operacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defeitos_origem', to='turnos.turnosetoroperacao')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='qualidade.qualidaderegistro')),
            ],
        ),
        migrations.AddIndex(
            model_name='qualidaderegistro',
            index=models.Index(fields=['turno', 'hora_revisao'], name='qualidade_q_turno_i_c0d950_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidaderegistro',
            index=models.Index(fields=['turno_op'], name='qualidade_q_turno_o_e25ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidaderegistro',
            index=models.Index(fields=['revisor', 'hora_revisao'], name='qualidade_q_revisor_9e1234_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualidaderegistro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_aprovada__gte', 0), ('quantidade_reprovada__gte', 0)), name='qual_reg_qtds_gte0'),
        ),
        migrations.AddConstraint(
            model_name='qualidaderegistro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_aprovada__gt', 0), ('quantidade_reprovada__gt', 0), _connector='OR'), name='qual_reg_revisao_nao_vazia'),
        ),
        migrations.AddIndex(
            model_name='qualidadedetalhe',
            index=models.Index(fields=['registro'], name='qualidade_q_registr_d3da08_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidadedetalhe',
            index=models.Index(fields=['defeito'], name='qualidade_q_defeito_6828b9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidadedetalhe',
            index=models.Index(fields=['operacao'], name='qualidade_q_operaca_721fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='qualidadedetalhe',
            index=models.Index(fields=['setor'], name='qualidade_q_setor_i_748f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualidadedetalhe',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_defeito__gt', 0)), name='qual_det_qtd_defeito_gt0'),
        ),
    ]
