import test from 'node:test'
import assert from 'node:assert/strict'
import type { PlanejamentoTurnoDashboardV2 } from '@/types'

const moduloKanbanOperacionalUrl = new URL('./kanban-operacional-turno.ts', import.meta.url)
const {
  construirColunasKanbanOperacional,
  resumirFluxoParaleloDemandaKanban,
}: typeof import('./kanban-operacional-turno') = await import(moduloKanbanOperacionalUrl.href)

function criarPlanejamentoTeste(): PlanejamentoTurnoDashboardV2 {
  return {
    origem: 'aberto',
    turno: {
      id: 'turno-1',
      iniciadoEm: '2026-04-16T08:00:00.000Z',
      encerradoEm: null,
      status: 'aberto',
      operadoresDisponiveis: 8,
      minutosTurno: 510,
      observacao: null,
    },
    operadores: [],
    ops: [],
    setoresAtivos: [
      {
        id: 'turno-setor-preparacao',
        turnoId: 'turno-1',
        setorId: 'setor-preparacao',
        setorCodigo: 10,
        setorNome: 'Preparação',
        quantidadePlanejada: 100,
        quantidadeRealizada: 20,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 20,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 20,
        qrCodeToken: 'qr-preparacao',
        operadoresAlocados: 3,
        capacidadeMinutosTotal: 1530,
        capacidadeMinutosRestante: 930,
        eficienciaRequeridaPct: 39.2,
        diagnosticoCapacidade: 'dentro_capacidade',
        status: 'em_andamento',
        iniciadoEm: '2026-04-16T08:00:00.000Z',
        encerradoEm: null,
      },
      {
        id: 'turno-setor-frente',
        turnoId: 'turno-1',
        setorId: 'setor-frente',
        setorCodigo: 20,
        setorNome: 'Frente',
        quantidadePlanejada: 100,
        quantidadeRealizada: 10,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 10,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 10,
        qrCodeToken: 'qr-frente',
        operadoresAlocados: 2,
        capacidadeMinutosTotal: 1020,
        capacidadeMinutosRestante: 0,
        eficienciaRequeridaPct: 117.647,
        diagnosticoCapacidade: 'acima_capacidade',
        status: 'em_andamento',
        iniciadoEm: '2026-04-16T08:00:00.000Z',
        encerradoEm: null,
      },
      {
        id: 'turno-setor-costa',
        turnoId: 'turno-1',
        setorId: 'setor-costa',
        setorCodigo: 30,
        setorNome: 'Costa',
        quantidadePlanejada: 100,
        quantidadeRealizada: 0,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 0,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 0,
        qrCodeToken: 'qr-costa',
        operadoresAlocados: 1,
        capacidadeMinutosTotal: 510,
        capacidadeMinutosRestante: 410,
        eficienciaRequeridaPct: 19.608,
        diagnosticoCapacidade: 'dentro_capacidade',
        status: 'aberta',
        iniciadoEm: null,
        encerradoEm: null,
      },
      {
        id: 'turno-setor-montagem',
        turnoId: 'turno-1',
        setorId: 'setor-montagem',
        setorCodigo: 40,
        setorNome: 'Montagem',
        quantidadePlanejada: 50,
        quantidadeRealizada: 0,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 0,
        cargaPlanejadaTp: 50,
        cargaRealizadaTp: 0,
        qrCodeToken: 'qr-montagem',
        operadoresAlocados: 1,
        capacidadeMinutosTotal: 510,
        capacidadeMinutosRestante: 510,
        eficienciaRequeridaPct: 0,
        diagnosticoCapacidade: 'sem_carga',
        status: 'aberta',
        iniciadoEm: null,
        encerradoEm: null,
      },
    ],
    demandasSetor: [
      {
        id: 'demanda-op-nova-preparacao',
        turnoSetorId: 'turno-setor-preparacao',
        turnoId: 'turno-1',
        turnoOpId: 'turno-op-nova',
        setorId: 'setor-preparacao',
        setorCodigo: 10,
        setorNome: 'Preparação',
        produtoId: 'produto-1',
        numeroOp: 'OP-100',
        produtoReferencia: 'REF-100',
        produtoNome: 'Produto novo',
        quantidadePlanejada: 100,
        quantidadeRealizada: 0,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 0,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 0,
        posicaoFila: 1,
        statusFila: 'liberada',
        quantidadePendenteSetor: 100,
        quantidadeLiberadaSetor: 100,
        quantidadeDisponivelApontamento: 100,
        quantidadeBloqueadaAnterior: 0,
        setorAnteriorId: null,
        setorAnteriorCodigo: null,
        setorAnteriorNome: null,
        status: 'aberta',
        iniciadoEm: null,
        encerradoEm: null,
        turnoSetorOpLegacyId: null,
      },
      {
        id: 'demanda-op-carryover-preparacao',
        turnoSetorId: 'turno-setor-preparacao',
        turnoId: 'turno-1',
        turnoOpId: 'turno-op-carryover',
        setorId: 'setor-preparacao',
        setorCodigo: 10,
        setorNome: 'Preparação',
        produtoId: 'produto-2',
        numeroOp: 'OP-200',
        produtoReferencia: 'REF-200',
        produtoNome: 'Carry-over',
        quantidadePlanejada: 100,
        quantidadeRealizada: 100,
        quantidadeConcluida: 100,
        progressoOperacionalPct: 100,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 100,
        posicaoFila: null,
        statusFila: 'concluida_setor',
        quantidadePendenteSetor: 0,
        quantidadeLiberadaSetor: 100,
        quantidadeDisponivelApontamento: 0,
        quantidadeBloqueadaAnterior: 0,
        setorAnteriorId: null,
        setorAnteriorCodigo: null,
        setorAnteriorNome: null,
        status: 'concluida',
        iniciadoEm: '2026-04-15T08:00:00.000Z',
        encerradoEm: '2026-04-15T12:00:00.000Z',
        turnoSetorOpLegacyId: null,
      },
      {
        id: 'demanda-op-carryover-frente',
        turnoSetorId: 'turno-setor-frente',
        turnoId: 'turno-1',
        turnoOpId: 'turno-op-carryover',
        setorId: 'setor-frente',
        setorCodigo: 20,
        setorNome: 'Frente',
        produtoId: 'produto-2',
        numeroOp: 'OP-200',
        produtoReferencia: 'REF-200',
        produtoNome: 'Carry-over',
        quantidadePlanejada: 100,
        quantidadeRealizada: 10,
        quantidadeConcluida: 10,
        progressoOperacionalPct: 10,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 10,
        posicaoFila: 1,
        statusFila: 'parcial',
        quantidadePendenteSetor: 90,
        quantidadeLiberadaSetor: 40,
        quantidadeDisponivelApontamento: 30,
        quantidadeBloqueadaAnterior: 60,
        setorAnteriorId: 'setor-preparacao',
        setorAnteriorCodigo: 10,
        setorAnteriorNome: 'Preparação',
        status: 'em_andamento',
        iniciadoEm: '2026-04-16T09:00:00.000Z',
        encerradoEm: null,
        turnoSetorOpLegacyId: null,
      },
      {
        id: 'demanda-op-carryover-costa',
        turnoSetorId: 'turno-setor-costa',
        turnoId: 'turno-1',
        turnoOpId: 'turno-op-carryover',
        setorId: 'setor-costa',
        setorCodigo: 30,
        setorNome: 'Costa',
        produtoId: 'produto-2',
        numeroOp: 'OP-200',
        produtoReferencia: 'REF-200',
        produtoNome: 'Carry-over',
        quantidadePlanejada: 100,
        quantidadeRealizada: 0,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 0,
        cargaPlanejadaTp: 100,
        cargaRealizadaTp: 0,
        posicaoFila: 1,
        statusFila: 'liberada',
        quantidadePendenteSetor: 100,
        quantidadeLiberadaSetor: 10,
        quantidadeDisponivelApontamento: 10,
        quantidadeBloqueadaAnterior: 90,
        setorAnteriorId: 'setor-frente',
        setorAnteriorCodigo: 20,
        setorAnteriorNome: 'Frente',
        status: 'aberta',
        iniciadoEm: null,
        encerradoEm: null,
        turnoSetorOpLegacyId: null,
      },
      {
        id: 'demanda-op-bloqueada-montagem',
        turnoSetorId: 'turno-setor-montagem',
        turnoId: 'turno-1',
        turnoOpId: 'turno-op-bloqueada',
        setorId: 'setor-montagem',
        setorCodigo: 40,
        setorNome: 'Montagem',
        produtoId: 'produto-3',
        numeroOp: 'OP-300',
        produtoReferencia: 'REF-300',
        produtoNome: 'Bloqueada',
        quantidadePlanejada: 50,
        quantidadeRealizada: 0,
        quantidadeConcluida: 0,
        progressoOperacionalPct: 0,
        cargaPlanejadaTp: 50,
        cargaRealizadaTp: 0,
        posicaoFila: 2,
        statusFila: 'em_fila',
        quantidadePendenteSetor: 50,
        quantidadeLiberadaSetor: 0,
        quantidadeDisponivelApontamento: 0,
        quantidadeBloqueadaAnterior: 50,
        setorAnteriorId: 'setor-costa',
        setorAnteriorCodigo: 30,
        setorAnteriorNome: 'Costa',
        status: 'planejada',
        iniciadoEm: null,
        encerradoEm: null,
        turnoSetorOpLegacyId: null,
      },
    ],
    secoesSetorOp: [],
    operacoesSecao: [],
    eficienciaOperacional: undefined,
  }
}

test('monta o kanban com OP nova, carry-over parcial, setor concluido, fracionamento real e fila aguardando liberacao', () => {
  const colunas = construirColunasKanbanOperacional(criarPlanejamentoTeste())

  assert.deepEqual(
    colunas.map((coluna) => coluna.setor.setorNome),
    ['Preparação', 'Frente', 'Costa', 'Montagem']
  )

  const preparacao = colunas[0]
  const frente = colunas[1]
  const costa = colunas[2]
  const montagem = colunas[3]

  assert.equal(preparacao?.demandasAtivas.length, 1)
  assert.equal(preparacao?.demandasEmQuadro.length, 1)
  assert.equal(preparacao?.demandasEmQuadro[0]?.numeroOp, 'OP-100')
  assert.equal(preparacao?.capacidadeComprometida, 600)

  assert.equal(frente?.demandasAtivas.length, 1)
  assert.equal(frente?.demandasEmQuadro.length, 1)
  assert.equal(frente?.demandasEmQuadro[0]?.statusFila, 'parcial')
  assert.equal(frente?.setor.diagnosticoCapacidade, 'acima_capacidade')
  assert.equal(frente?.capacidadeComprometida, 1020)

  assert.equal(costa?.demandasAtivas.length, 1)
  assert.equal(costa?.demandasEmQuadro.length, 1)
  assert.equal(costa?.demandasEmQuadro[0]?.numeroOp, 'OP-200')
  assert.equal(costa?.demandasEmQuadro[0]?.quantidadeLiberadaSetor, 10)

  assert.equal(montagem?.demandasAtivas.length, 1)
  assert.equal(montagem?.demandasEmQuadro.length, 0)
  assert.equal(montagem?.aguardandoLiberacao, 1)
})

test('resume o fluxo paralelo do card do kanban destacando Frente e Costa simultaneas', () => {
  const resumo = resumirFluxoParaleloDemandaKanban(
    {
      posicoesFluxoAtivas: [
        {
          etapa: 'frente',
          setorId: 'setor-frente',
          setorCodigo: 20,
          setorNome: 'Frente',
          tipoDependenciaEntrada: 'sequencial',
          tipoDependenciaSaida: 'sequencial',
          quantidadePlanejada: 100,
          quantidadeConcluida: 40,
          quantidadeLiberada: 40,
          quantidadeDisponivel: 30,
          quantidadePendente: 60,
          quantidadeBloqueadaSincronizacao: 0,
          posicaoFila: 1,
          statusFila: 'parcial',
        },
        {
          etapa: 'costa',
          setorId: 'setor-costa',
          setorCodigo: 30,
          setorNome: 'Costa',
          tipoDependenciaEntrada: 'sequencial',
          tipoDependenciaSaida: 'sequencial',
          quantidadePlanejada: 100,
          quantidadeConcluida: 25,
          quantidadeLiberada: 40,
          quantidadeDisponivel: 15,
          quantidadePendente: 75,
          quantidadeBloqueadaSincronizacao: 0,
          posicaoFila: 1,
          statusFila: 'parcial',
        },
        {
          etapa: 'montagem',
          setorId: 'setor-montagem',
          setorCodigo: 40,
          setorNome: 'Montagem',
          tipoDependenciaEntrada: 'join_parcial',
          tipoDependenciaSaida: 'sequencial',
          quantidadePlanejada: 100,
          quantidadeConcluida: 0,
          quantidadeLiberada: 25,
          quantidadeDisponivel: 25,
          quantidadePendente: 100,
          quantidadeBloqueadaSincronizacao: 75,
          posicaoFila: 1,
          statusFila: 'em_fila',
        },
      ],
      quantidadeSincronizadaMontagem: 25,
      quantidadeBloqueadaSincronizacao: 75,
    },
    {
      etapaFluxoChave: 'frente',
      setorNome: 'Frente',
      quantidadeSincronizadaMontagem: 25,
      quantidadeBloqueadaSincronizacao: 75,
    }
  )

  assert.deepEqual(
    {
      etapaAtual: resumo.etapaAtual,
      fluxoParaleloAtivo: resumo.fluxoParaleloAtivo,
      posicoesSimultaneas: resumo.posicoesSimultaneas.map((posicao) => posicao.etapa),
      quantidadeSincronizadaMontagem: resumo.quantidadeSincronizadaMontagem,
      quantidadeBloqueadaSincronizacao: resumo.quantidadeBloqueadaSincronizacao,
    },
    {
      etapaAtual: 'frente',
      fluxoParaleloAtivo: true,
      posicoesSimultaneas: ['costa'],
      quantidadeSincronizadaMontagem: 25,
      quantidadeBloqueadaSincronizacao: 75,
    }
  )
})
