-- ============================================================
-- SPRINT 6.1 — Setores (V2)
-- Migração incremental sobre o schema atual
-- ============================================================

CREATE TABLE IF NOT EXISTS setores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  nome VARCHAR(100) NOT NULL UNIQUE,
  ativo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO setores (nome)
VALUES
  ('Preparação'),
  ('Frente'),
  ('Costa'),
  ('Montagem'),
  ('Finalização')
ON CONFLICT (nome) DO NOTHING;

ALTER TABLE setores ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "leitura_setores_autenticados" ON setores
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- Validações
-- ============================================================
SELECT COUNT(*) AS total_setores FROM setores;

SELECT 'setores ok'
WHERE EXISTS (
  SELECT 1
  FROM information_schema.tables
  WHERE table_name = 'setores'
);
