-- ============================================================
-- SPRINT 6.1 — Setores (V2)
-- Migração incremental sobre o schema atual
-- ============================================================

CREATE TABLE IF NOT EXISTS setores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  nome VARCHAR(100) NOT NULL UNIQUE,
  modo_apontamento VARCHAR(30) NOT NULL DEFAULT 'producao_padrao'
    CHECK (modo_apontamento IN ('producao_padrao', 'revisao_qualidade')),
  ativo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE setores
ADD COLUMN IF NOT EXISTS modo_apontamento VARCHAR(30) NOT NULL DEFAULT 'producao_padrao';

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'setores_modo_apontamento_check'
      AND conrelid = 'setores'::regclass
  ) THEN
    ALTER TABLE setores
      ADD CONSTRAINT setores_modo_apontamento_check
      CHECK (modo_apontamento IN ('producao_padrao', 'revisao_qualidade'));
  END IF;
END $$;

INSERT INTO setores (nome, modo_apontamento)
VALUES
  ('Preparação', 'producao_padrao'),
  ('Frente', 'producao_padrao'),
  ('Costa', 'producao_padrao'),
  ('Montagem', 'producao_padrao'),
  ('Finalização', 'producao_padrao'),
  ('Qualidade', 'revisao_qualidade')
ON CONFLICT (nome) DO UPDATE
SET modo_apontamento = EXCLUDED.modo_apontamento;

ALTER TABLE setores ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "leitura_setores_autenticados" ON setores
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- Validações
-- ============================================================
SELECT COUNT(*) AS total_setores FROM setores;

SELECT 'setores ok'
WHERE EXISTS (
  SELECT 1
  FROM information_schema.tables
  WHERE table_name = 'setores'
);

SELECT 'setores.modo_apontamento ok'
WHERE EXISTS (
  SELECT 1
  FROM information_schema.columns
  WHERE table_name = 'setores'
    AND column_name = 'modo_apontamento'
);
