# Generated by Django 5.2.15 on 2026-06-04 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('numero_patrimonio', models.CharField(blank=True, max_length=50)),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('parada', 'Parada'), ('manutencao', 'Manutencao'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['situacao', 'codigo'], name='cadastros_m_situaca_cf4235_idx'), models.Index(fields=['qr_code_token'], name='cadastros_m_qr_code_6733e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('modo_apontamento', models.CharField(choices=[('producao_padrao', 'Producao padrao'), ('revisao_qualidade', 'Revisao qualidade')], default='producao_padrao', max_length=30)),
                ('sequencia_fluxo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sequencia_fluxo', 'nome'],
                'indexes': [models.Index(fields=['situacao', 'sequencia_fluxo'], name='cadastros_s_situaca_bc7d14_idx'), models.Index(fields=['modo_apontamento'], name='cadastros_s_modo_ap_9ac76c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tempo_padrao_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('meta_hora', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_dia', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('imagem_url', models.TextField(blank=True)),
                ('qr_code_token', models.CharField(max_length=64, unique=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='cadastros.maquina')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='cadastros.setor')),
                ('tipo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='cadastros.tipomaquina')),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['setor', 'situacao'], name='cadastros_o_setor_i_fdb838_idx'), models.Index(fields=['qr_code_token'], name='cadastros_o_qr_code_8e2b32_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tempo_padrao_min__gt', 0)), name='operacao_tp_positivo')],
            },
        ),
    ]
