# Generated by Django 5.2.15 on 2026-06-04 23:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.DateField(unique=True)),
                ('meta_pecas', models.PositiveIntegerField()),
                ('dias_produtivos', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['competencia'], name='metas_metam_compete_959e71_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('meta_pecas__gt', 0)), name='meta_mensal_pecas_gt0'), models.CheckConstraint(condition=models.Q(('dias_produtivos__gte', 1), ('dias_produtivos__lte', 31)), name='meta_mensal_dias_validos')],
            },
        ),
    ]
