# Generated by Django 5.2.15 on 2026-06-04 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem_frente_url', models.TextField(blank=True)),
                ('imagem_costa_url', models.TextField(blank=True)),
                ('tp_produto_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['ativo', 'nome'], name='produtos_pr_ativo_09472c_idx'), models.Index(fields=['codigo'], name='produtos_pr_codigo_0900e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoOperacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencia', models.PositiveIntegerField()),
                ('versao_roteiro', models.PositiveIntegerField(default=1)),
                ('vigente', models.BooleanField(default=True)),
                ('substituido_em', models.DateTimeField(blank=True, null=True)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cadastros.operacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiro', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto', 'versao_roteiro', 'sequencia'],
                'indexes': [models.Index(fields=['produto', 'vigente', 'sequencia'], name='produtos_pr_produto_aef6ad_idx'), models.Index(fields=['operacao'], name='produtos_pr_operaca_fb7629_idx')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'versao_roteiro', 'sequencia'), name='uniq_prod_versao_seq'), models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('produto', 'sequencia'), name='uniq_prod_seq_vigente'), models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('produto', 'operacao'), name='uniq_prod_operacao_vigente')],
            },
        ),
    ]
